### ISSUE TITLE
Build issue with 18.04 LTS on X86 PC

### ISSUE THREAD

**Issue by shimeng-wang** [NVIDIA/jetson-rdma-picoevb#11]
FATAL: parse error in symbol dump file
scripts/Makefile.modpost:93: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
Makefile:1675: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-121-generic'
Makefile:18: recipe for target 'modules' failed
make: *** [modules] Error 2

I am getting these errors when I run the ./build-for-pc-native.sh script.   

Environment is 18.04 LTS on X86 PC

**Comment by shimeng-wang** [comment]
I was able to build for 18.04 kernel by modifying the nvidia-ko-to-module-symvers script to add a "tab" to the end of every line in the generated Module.symvers.

**Comment by apexintern1** [comment]
Can you explain in detail, on how you resolved the issue? 
Thank you

**Comment by pateldipen1984-nv** [comment]
For kernel > 4.9 it seems it requires tab, so you need to reflect that int he nvidia-ko-to-module-symvers script based on which kernel version you choose.

**Comment by pyt-hnu** [comment]
> I was able to build for 18.04 kernel by modifying the nvidia-ko-to-module-symvers script to add a "tab" to the end of every line in the generated Module.symvers.

I meet same problem, can i ask how do you solve it.
