### ISSUE TITLE
Load kernel failed on Clara AGX with Tegra 5.10.65

### ISSUE THREAD

**Issue by hmzawz2** [NVIDIA/jetson-rdma-picoevb#15]
Last week I tried to build kernel_module with my Clara AGX, the operating system is tegra 5.10.65. After successfully built the kernel-module, I tried to load picoevb kernel and I met this:
```bash
(base) ubuntu@ubuntu:~/jetson-rdma-picoevb/kernel-module$ sudo insmod picoevb-rdma.ko
insmod: ERROR: could not insert module picoevb-rdma.ko: Unknown symbol in module
```
And I try to use `modinfo` show what symbol is unknown, I found:

```bash
(base) ubuntu@ubuntu:~/jetson-rdma-picoevb/kernel-module$ modinfo picoevb-rdma.ko | grep depends
depends:        nvidia-p2p
```
Then I used `modprobe` to insert nvidia-p2p, I got:
```
(base) ubuntu@ubuntu:~/jetson-rdma-picoevb/kernel-module$ sudo modprobe nvidia-p2p
modprobe: ERROR: could not insert 'nvidia_p2p': Exec format error
```

Later, I remembered that this platform opened dGPU support, but the project is for iGPU (but could it built for dPGU on native Clara AGX? Any one can answer this? Thanks in advance!). Fortunately I have another Clara AGX without dGPU, but its system is tegra 4.9.253. I successfully built and load kernel module.

So my question is: should this project only built on tegra 4.9 platform, or only built on iGPU mode? or both? Thanks in advance!

**Comment by pateldipen1984-nv** [comment]
If clara AGX uses dGPU and its modules are loaded, you need to unload them before trying iGPU use case. The exec error AFAIK is because of the kernel mismatch. What does modinfo of the nvidia_p2p and picoevb_rdma says? Also share the steps of how did you compile picoevb-rdma.ko?

**Comment by pateldipen1984-nv** [comment]
Closing this issue as I have not heard back. Please re-open if needed.
