### ISSUE TITLE
Facing a BUG

### ISSUE THREAD

**Issue by pyt-hnu** [NVIDIA/jetson-rdma-picoevb#16]
When i runnig "./rdma-cuda", the process will stall,like this.
![1689749589542](https://github.com/NVIDIA/jetson-rdma-picoevb/assets/119828553/9c32f3ed-427a-4553-8014-126da61dfffc)
 
and the result of "dmesg" is this,
![7de007c226b281e98cfaf831866e9e9](https://github.com/NVIDIA/jetson-rdma-picoevb/assets/119828553/5c5a4684-7c8d-42a1-89e6-2c4cb7a5c751)

**Comment by pateldipen1984-nv** [comment]
Please share the steps, how did you build the application and kernel module? what is the use case iGPU or dGPU?
