### ISSUE TITLE
Use of PCIe interface to send video from gstreamer to Artix-7 FPGA

### ISSUE THREAD

**Issue by jbolduc01** [NVIDIA/jetson-rdma-picoevb#3]
Hello,
I would like to know if we could use this minimal software package in order to capture video from a gstreamer pipeline and output the result through PCIe to a Artix-7 FPGA.

Is using a simple gstreamer pipeline like could give us access to video data to FPGA?
`gst-launch-1.0 videotestsrc ! video/x-raw,witdth=1920,height=1080 ! fakesink`

Regards,
Jérôme

**Comment by jbolduc01** [comment]
We plan to use a Jetson Nano module.

**Comment by swarren** [comment]
This project on its own won't achieve that, no. There is no GStreamer integration in the code. However, if you were to develop your own GStreamer plugin, you may be able to use this code as a reference for how to get the video data into an FPGA, or other PCIe device.
