### ISSUE TITLE
Build for PC on ubuntu 20.04

### ISSUE THREAD

**Issue by usberbt1** [NVIDIA/jetson-rdma-picoevb#6]
Hello,

When trying to build on Ubuntu 20.04 "build_for_pc_native.sh" I get problems with modpost:

ERROR: modpost: "nvidia_p2p_get_pages" [****/kernel-module/picoevb-rdma.ko] undefined!

NVIDIA_SRC_DIR and NVIDIA_KO are both found. I'm using Nvidia driver version 460 and CUDA 11.3.

Thank you,

**Comment by usberbt1** [comment]
It seems like this is related to using kernel 5 versus kernel 4. These modpost errors have been upgraded from warnings since 4. A workaround for the time being may be to add the flags "-i -k" to the makefile in kernel_modules.

**Comment by qigtang** [comment]
The solution cannot work. Adding "-i -k" can get it to build, but when running
```bash
sudo insmod ./picoevb-rdma.ko
```
get the error message

```bash
insmod: ERROR: could not insert module ./picoevb-rdma.ko: Unknown symbol in module
```

run 

``` bash
objdump -t ./picoevb-rdma.ko |grep nvidia
```
get output
```bash
0000000000000000         *UND*  0000000000000000 nvidia_p2p_dma_unmap_pages
0000000000000000         *UND*  0000000000000000 nvidia_p2p_get_pages
0000000000000000         *UND*  0000000000000000 nvidia_p2p_put_pages
0000000000000000         *UND*  0000000000000000 nvidia_p2p_dma_map_pages
0000000000000000         *UND*  0000000000000000 nvidia_p2p_free_page_table
```

Looks like in ubuntu 20.04, it cannot find the symbols in nvidia.ko

**Comment by hmzawz2** [comment]
ok, I met same problem as qigtang.
when i use modinfo with grep depend to check the picoevb-rdma.ko depends, the output is as following
`modinfo ./picoevb-rdma.ko | grep depend`

`depends:        nvidia-p2p`
and i try use modprobe to load nvidia-p2p, the output is
`sudo modprobe nvidia-p2p`

`modprobe: ERROR: could not insert 'nvidia_p2p': Exec format error`
But I do find the nvidia-p2p on my machine. Why it cannot load nvidia-p2p module? can anyone helps me?

**Comment by pyt-hnu** [comment]
I also meet same proble, and Is anyone solving it now.  ubuntu 20.04  /5.4.0-42-generic

**Comment by mianyan-echo** [comment]
@qigtang I also encountered the same problem. Did you solve this problem later?
