### ISSUE TITLE
Connection to a Numato Tagus using PCI slot

### ISSUE THREAD

**Issue by enarasanz** [NVIDIA/jetson-rdma-picoevb#7]
Hello, 
I am trying to run this project using a Numato Tagus connected to the PCI slot of the Jetson xavier using its 1 lane PCIe Gen2.0. 
I previously run your project using a picoevb and had it running. My problem now is that when I load the kernel module it seems it does not recognize the board. I was wondering if as I no longer use the M2 slot there would be a problem, but I saw that you used another card which uses the PCI slot that I am currently using, and the files used seem to be the same.

Besides, when I check the connections to the jetson Xavier I can't find my board. 

I was wondering if your driver may be used with this card ( probably you haven't check this specifically but may have an idea) and/or  if there are some minor changes that I could do to readjust the driver ( some indications of which files or code areas should be modified)

**Comment by pateldipen1984-nv** [comment]
are you still having the issue? closing this as its old, please file new issue.
